redis:
  # This is from a GCP Memorystore on the same network
  host: "10.73.37.219"
  #cache_callback: true
  #cache_parallel: true
  #port: 6379
  #password: ""

stratus:
  #rootPath: "/"
  container:
    #secretKey: ""
    image: "gcr.io/stratus-gcp-0/stratus"
    tag: "ubuntu"
  ogc:
    resources:
      cpu: 0.8
      maxCpu: 1.0
      mem: 1.0G
      maxMem: 1.5G
      #maxReplicas: 3
      #minReplicas: 1
  ui:
    resources:
    resources:
      cpu: 0.8
      maxCpu: 1.0
      mem: 1.0G
      maxMem: 1.5G
